import { createSlice } from "@reduxjs/toolkit";

const loadCartFromStorage = () => {
  if (typeof window === "undefined") return [];
  try {
    const saved = localStorage.getItem("shopmate_cart");
    return saved ? JSON.parse(saved) : [];
  } catch (error) {
    console.warn("Failed to read cart from localStorage", error);
    return [];
  }
};

const saveCartToStorage = (cart) => {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem("shopmate_cart", JSON.stringify(cart));
  } catch (error) {
    console.warn("Failed to save cart to localStorage", error);
  }
};

const cartSlice = createSlice({
  name: "cart",
  initialState: {
    cart: loadCartFromStorage(),
  },
  reducers: {
    addToCart(state, action) {
      const { product, quantity } = action.payload; // Expecting payload to be an object with product and quantity

      const existingItem = state.cart.find(
        (item) => item.product.id === product.id // Check if the product is already in the cart eg down
      );

      if (existingItem) {
        existingItem.quantity += quantity; // If it exists, just update the quantity
      } else {
        state.cart.push({ product, quantity }); // If it doesn't exist, add a new item to the cart
      }

      saveCartToStorage(state.cart);
    },

    removeFromCart(state, action) {
      state.cart = state.cart.filter(
        (item) => item.product.id !== action.payload // Expecting payload to be the product ID to remove
      );
      saveCartToStorage(state.cart);
    },

    updateCartQuantity(state, action) {
      const item = state.cart.find(
        (item) => item.product.id === action.payload.id
      );
      if (item) {
        item.quantity = action.payload.quantity;
      }
      saveCartToStorage(state.cart);
    },

    clearCart(state) {
      state.cart = []; // Clear the cart by setting it to an empty array
      saveCartToStorage(state.cart);
    },
  },
});

export const { addToCart, removeFromCart, updateCartQuantity, clearCart } =
  cartSlice.actions; // Exporting the action creators generated by createSlice for use in components to dispatch actions to the store.

export default cartSlice.reducer;
//[1,2,3,4,5] id=2 so filter will return [1,3,4,5] and updateCartQuantity will find the item with id=2 and update its quantity